### ISSUE TITLE
VS stopped responding for 28 seconds. Disabling the extension Start Page+ 0.14.3 might help

### ISSUE THREAD

**Issue by MagicAndre1981** [luminous-software/start-page-plus#31]
### Installed product versions
- Visual Studio: 2019 16.3.3
- This extension: 0.14.3

### Description

I opened/closed several solutions and noticed that VS shows a message that StartPage+ causes a delay of 28s.

![image](https://user-images.githubusercontent.com/8274816/66573671-587f1280-eb73-11e9-88ca-639a61bf3496.png)

I have no real steps to repro it.

**Comment by yannduran** [comment]
Did you notice any lag from the window displaying? Is this happening more than once?

**Comment by MagicAndre1981** [comment]
I can't really remember what I did and if VS was unresponsive until I suddenly saw this message.

**Comment by yannduran** [comment]
I've had spurious notifications about other extensions when VS got tangled up for some reason.

Please let me know if you continue to get this message.

**Comment by MagicAndre1981** [comment]
I got it now after opening a solution. Maybe [closing/reopen startpage after solution load/close](https://github.com/luminous-software/start-page-plus/issues/63) will "fix" it.

**Comment by yannduran** [comment]
The only thing that should really take **any** conceivable amount of time (and it never has for me) is loading the _Developer News_ items. There's only ten of them to load. But that's done asynchronously, when the window is first constructed, unless _Refresh_ is clicked, so that **_shouldn't_** be the problem.

Or reading from the registry to pick up the _recent items_. But a refresh of that list happens so fast that you can't even see a flicker! I even cleared the list first to try to give a visual clue that the items actually did get refreshed. I did the same with the news list, so I know it should have some effect, but still nothing.

Do you have decent broadband internet? How long does it take to refresh the _Developer News_ items?

There definitely shouldn't be a **_28 second delay_** opening a file, that nuts. Weird! I assume that you're opening the file by clicking on an item in Start Page+. Yeah, of course you would be.

Nobody else has mentioned it so far, so I don't know what it could be.

**Comment by MagicAndre1981** [comment]
ok, hopefully I can hide news in later previews as I don't like it and it wastes a lot of space.

**Comment by yannduran** [comment]
I never used to read much of the news in VS 2017, But I became a convert when I was developing the _Developer News_ extension.

As for being able to hide it, I don't know about that one. Don't get me wrong, I'm all about users having choices, I just don't see what purpose it'd achieve to be able to hide it. You'd just end up with 2 extra-wide columns that were never meant to be so wide. I really see NO benefit to anyone.

**Comment by MagicAndre1981** [comment]
But I see it. Recent projects can have long paths, this requires most space, the column with the command entries can be made much smaller and the completely useless developer news column only wastes space.

**Comment by yannduran** [comment]
You'll love the _Favorites_ tab, I promise you! It'll give you the ability to create columns to add groups of projects that make sense to you. I envision that once people get this set up the way they like, that they won't need the _Recent Items_ list much, if at all. 

I even have always had in mind the ability to make the _Favorites_ tab (or any other tab) to be that tab that _Start Page+_ opens on, allowing people like yourself to bypass the _Start_ tab altogether. And a user has added issue luminous-software/start-page-plus-64-bit#21 with the same idea.

The _Start_ tab wasn't created for **advanced** users like yourself. It was created to bring back a **non-modal** start page, that brought back what was lost from VS 2017, without losing anything from VS 2019's _Start Window_.

Btw, is this performance problem still happening for you? I apologise for the basic nature of the following questions (but I have to ask them):
- have you restarted Visual Studio? 
- have you restarted Windows? 
- did you installed any other extensions just before this started happening for you?

With no other users reporting this problem, I find it hard to figure out what Start Page+ could be doing to cause it. It's far more likely that there could be some issue on your machine. You didn't get this issue for a long time, right? 

Looking at the message again, it didn't actually say that _SP+_ was the **cause** of the delay, just that "_VS had stopped responding for 28 seconds, and that it disabling SP+ **_might_** help_".

If you agree this is a possibility, would you mind if we closed this issue? I'd like to keep the issues list as short as possible. If you need to, it can always be re-opened later. If you're not able to re-open it, I'll certainly do that for you.

**Comment by yannduran** [comment]
I've edited the title to give a more **accurate** representation of the issue, whether it's _open_ or _closed_, by using the _actual text_ from the message. I hope you don't mind.

**Comment by MagicAndre1981** [comment]
I restarted VS and Windows several times. I need the version with auto close to see if it improves situation.

**Comment by NetMage** [comment]
I just installed Start Page + and the first time I opened a Recent Item that was a (very simple) solution, I got the same message for six seconds. I added another extension (restarting VS2019) and noticed when I click on the solution in Open a Recent Item there is a six second delay (with a Loading message in the bottom status bar) before the Solution Explorer populates, and I assume that delay is when the extension is not responding.

**Comment by BOBJohnson** [comment]
I get the message every time. If there is lag I haven't noticed it. I told VS to stop nagging me about it because if there is lag on my PC it isn't noticeable.

On an unrelated note, is there somewhere I can go to download Preview 4 or 5? I'm still on Preview 3, and when I go to the Marketplace page it's still just Preview 3.

I saw this post last year: https://developercommunity.visualstudio.com/content/idea/435168/make-the-visual-studio-2019-start-window-non-modal.html <- but then as far as I can tell, preview 4 was never rolled out.

**Comment by yannduran** [comment]
Sorry Bob, I just saw your question about _Preview 4_. _Preview 3_ was actually the last public release. I then had some personal issues (lost a loved one) and it's only just now that I've started coding again.

The next release will be **v1.0**, with a release date of about May 8th. Checkout the [v1.0](https://github.com/luminous-software/start-page-plus/milestone/5) milestone link to see what's been done already and what's still coming.

Nobody's reported this problem recently, so I'll close this issue now. I'm happy to re-open it if required.

**Comment by MagicAndre1981** [comment]
> Nobody's reported this problem recently, so I'll close this issue now. I'm happy to re-open it if required.

Likely because every clicked "don't report extension again". But I still see it:

![StartPlus_delay_VS2019](https://user-images.githubusercontent.com/8274816/81376227-5f6b0500-9103-11ea-8b59-e3959e682f88.png)

> The next release will be v1.0, with a release date of about May 8th. 

can't wait to test the new version

**Comment by yannduran** [comment]
I think I may have found something that _could_ cause this type of issue, although I've never seen it personally.

Although Visual Studio only shows us 10 MRU items, able to be increased to 25 if I remember correctly, quite a long list of recent items is actually stored by it. The longer the list becomes the more the delay will be in fetching/processing the items. This happens when the window is first opened in a session, or of course when the _Refresh_ button is clicked.

So this could explain why some people were getting the notification, and hopefully selecting a finite number (default is 50) the delay will become negligible.
In v1.0 I've introduced a setting where you can limit the number of recent items to whatever you want.

**Comment by MagicAndre1981** [comment]
ok, I'll test this, I have a long list (some pinned, some not) because I don't switch branches in a working copy, I checkout own working copies for different branches so I have longer lists.

**Comment by yannduran** [comment]
Setting *Recent Items to Display* to 1000 with the latest version that I'm dogfooding gives me projects/solutions all the way back to Feb 2017.

A total of 274 items! 

I don't know exactly how many items VS will store, but the ability to limit the number retrieved/displayed to whatever **you** want should help performance.

**Comment by MagicAndre1981** [comment]
@yannduran with 1.0 I haven't see the warning, perf is better compared to old preview 👍

**Comment by yannduran** [comment]
@MagicAndre1981 

That great to hear! Did you change the setting for the number of items to display, or did you just leave the default?

**Comment by MagicAndre1981** [comment]
@yannduran I changed nothing.

**Comment by yannduran** [comment]
@BOBJohnson 

How about you Bob, what's your experience with **v1.0**?
